### ISSUE TITLE
Big problem 

### ISSUE THREAD

**Issue by ArmyXomuiL** [udark/underdark-cocoa#2]
dyld: Library not loaded: @rpath/MSWeakTimer.framework/MSWeakTimer
  Referenced from: /private/var/mobile/Containers/Bundle/Application/B54CB0A8-E990-473A-8BBA-45878B280262/Sync.app/Frameworks/Underdark.framework/Underdark
  Reason: image not found

<img width="854" alt="1" src="https://cloud.githubusercontent.com/assets/8521655/16806380/58044562-4925-11e6-9544-ce50ff105ae3.png">
<img width="642" alt="2" src="https://cloud.githubusercontent.com/assets/8521655/16806381/5890175e-4925-11e6-91a0-31c7c238c25d.png">

**Comment by virl** [comment]
Hello!
Thanks for the feedback.

Are you linking Swift or Obj-C application with Underdark?

**Comment by ArmyXomuiL** [comment]
Hello!

I started a new project at Swift. Use "Linking pre-built version".
In Obj-C project I have a similar problem.

**Comment by virl** [comment]
It's a bit different how to link with Obj-C and Swift.
For Swift linking example, you can look at UDApp in this repository and do the same.

**Comment by bhadkiaftab** [comment]
/Users/aftabbhadki/Library/Developer/Xcode/DerivedData/UDApp-fiigzhkcqzzknpcqtsdvtmsnxipu/Build/Intermediates/UDApp.build/Debug-iphoneos/UDApp.build/Script-D54A1D7F1D50805900FC6B6A.sh: line 2: /usr/local/bin/carthage: No such file or directory

getting this error

**Comment by virl** [comment]
@bhadkiaftab Just install Carthage with homebrew as described in README: `brew install carthage`
