### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by luandro** [udark/underdark-cocoa#3]
It would be the most awesome thing ever to have this as a [React-Native](https://facebook.github.io/react-native/) plugin for both iOS and Android. I personally have no experience with Java os C environments, so I'm not sure what needs to be done.

You could [wrap native code in a manager](http://facebook.github.io/react-native/releases/0.36/docs/native-modules-ios.html#native-modules) or take a look at [react-native-invoke,](https://github.com/wix/react-native-invoke) you can:

> Invoke any native code directly from Javascript in React Native (without wrapping it first with a native manager)

**Comment by virl** [comment]
@luandro Thanks for the request, I will look into it.

**Comment by alexkendall** [comment]
Already did.

https://github.com/alexkendall/react-native-bluetooth-cross-platform It uses underdark and is cross platform. I need to clean up the documentation and feel free to contribute, but it uses underdark and is completely cross platform.

**Comment by luandro** [comment]
I'll check it out once I have some time. That's awesome, thanks.
