### ISSUE TITLE
While receiving large file the screen freezes

### ISSUE THREAD

**Issue by paultnp** [udark/underdark-cocoa#4]
When one device is receiving the file in the below delegate
    func transport(transport: UDTransport, link: UDLink, didReceiveFrame data: NSData)
    {
    }

The iPhone screen freezes and one can not move to any other screen. Is there any way that file could be received in background queue or in any other separate thread so that screen does not freeze 

Thanks

**Comment by virl** [comment]
@paultnp Hello! Yes, you can specify the queue when calling configureTransport().

**Comment by paultnp** [comment]
Thanks for quick reply @virl 
can you give some example code for the same
sorry I have just started with this library and stuck in this step

**Comment by paultnp** [comment]
Thanks @virl your suggestion worked
