### ISSUE TITLE
Very Frequently giving bad access 

### ISSUE THREAD

**Issue by arpanCode** [udark/underdark-cocoa#5]
Hi , 
Form last 2 weeks i ma experiencing very frequent crash due to Bad Access while 
[NSNetService publishWithServer:]block invoke. 
I have debug this bad access found when you frequently  start & stop NOde , after 2 to 3 attempts its giving Bad access. Can you please help ??

**Comment by virl** [comment]
@arpanCode Thanks for the bugreport.
Yes, this code had multithreading issues and I've recently fixed them. Fix will be available in upcoming update.
